version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2024.5.5
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
