# coding: utf-8

# flake8: noqa
"""
    Solar Manager external API 

    This is a Solar Manager external communication service

    The version of the OpenAPI document: 1.19.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.arrows_schema import ArrowsSchema
from openapi_client.models.autarchy import Autarchy
from openapi_client.models.battery import Battery
from openapi_client.models.battery_charging_mode_and_settings_schema import BatteryChargingModeAndSettingsSchema
from openapi_client.models.car_charger_payload_schema import CarChargerPayloadSchema
from openapi_client.models.car_chargers import CarChargers
from openapi_client.models.charged import Charged
from openapi_client.models.charging_mode_schema import ChargingModeSchema
from openapi_client.models.common_seasons import CommonSeasons
from openapi_client.models.consumption import Consumption
from openapi_client.models.consumption_statistics_sensor_schema import ConsumptionStatisticsSensorSchema
from openapi_client.models.customer_response_schema import CustomerResponseSchema
from openapi_client.models.data_in_interval_schema import DataInIntervalSchema
from openapi_client.models.data_schema import DataSchema
from openapi_client.models.device_schema import DeviceSchema
from openapi_client.models.discharged import Discharged
from openapi_client.models.dynamic_tariffs_schema import DynamicTariffsSchema
from openapi_client.models.forecast_schema import ForecastSchema
from openapi_client.models.gateway_chart_data_schema import GatewayChartDataSchema
from openapi_client.models.gateway_detailed_response_schema import GatewayDetailedResponseSchema
from openapi_client.models.gateway_info_schema import GatewayInfoSchema
from openapi_client.models.gateway_interval_consumption_schema import GatewayIntervalConsumptionSchema
from openapi_client.models.general_values_production_consumption_battery_schema import GeneralValuesProductionConsumptionBatterySchema
from openapi_client.models.heatpumps import Heatpumps
from openapi_client.models.inverter_settings_schema import InverterSettingsSchema
from openapi_client.models.last_data_device_schema import LastDataDeviceSchema
from openapi_client.models.last_data_from_gateway_schema import LastDataFromGatewaySchema
from openapi_client.models.last_sensor_data_response_schema import LastSensorDataResponseSchema
from openapi_client.models.last_sensor_response_schema import LastSensorResponseSchema
from openapi_client.models.model1 import Model1
from openapi_client.models.model10 import Model10
from openapi_client.models.model12 import Model12
from openapi_client.models.model14 import Model14
from openapi_client.models.model16 import Model16
from openapi_client.models.model18 import Model18
from openapi_client.models.model19 import Model19
from openapi_client.models.model2 import Model2
from openapi_client.models.model20 import Model20
from openapi_client.models.model21 import Model21
from openapi_client.models.model22 import Model22
from openapi_client.models.model23 import Model23
from openapi_client.models.model24 import Model24
from openapi_client.models.model25 import Model25
from openapi_client.models.model26 import Model26
from openapi_client.models.model27 import Model27
from openapi_client.models.model28 import Model28
from openapi_client.models.model29 import Model29
from openapi_client.models.model30 import Model30
from openapi_client.models.model31 import Model31
from openapi_client.models.model32 import Model32
from openapi_client.models.model33 import Model33
from openapi_client.models.model35 import Model35
from openapi_client.models.model36 import Model36
from openapi_client.models.model38 import Model38
from openapi_client.models.model39 import Model39
from openapi_client.models.model4 import Model4
from openapi_client.models.model40 import Model40
from openapi_client.models.model6 import Model6
from openapi_client.models.model7 import Model7
from openapi_client.models.model8 import Model8
from openapi_client.models.model9 import Model9
from openapi_client.models.model_from import ModelFrom
from openapi_client.models.monitoring import Monitoring
from openapi_client.models.overview_schema import OverviewSchema
from openapi_client.models.production import Production
from openapi_client.models.sensor_data_response_schema import SensorDataResponseSchema
from openapi_client.models.sensor_tag_schema import SensorTagSchema
from openapi_client.models.sensor_tariff_schema import SensorTariffSchema
from openapi_client.models.single_sensor_response_schema import SingleSensorResponseSchema
from openapi_client.models.smart_plug_charging_mode_schema import SmartPlugChargingModeSchema
from openapi_client.models.statistics_of_gateway_response_schema import StatisticsOfGatewayResponseSchema
from openapi_client.models.status import Status
from openapi_client.models.tariff import Tariff
from openapi_client.models.total_energy import TotalEnergy
from openapi_client.models.user_schema import UserSchema
from openapi_client.models.user_settings_schema import UserSettingsSchema
from openapi_client.models.v2_x_payload_schema import V2XPayloadSchema
from openapi_client.models.v2x_chargers import V2xChargers
from openapi_client.models.versions import Versions
from openapi_client.models.water_heater_payload_schema import WaterHeaterPayloadSchema
from openapi_client.models.water_heaters import WaterHeaters
from openapi_client.models.winter_season import WinterSeason
