# coding: utf-8

"""
    Solar Manager external API 

    This is a Solar Manager external communication service

    The version of the OpenAPI document: 1.19.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, conlist
from openapi_client.models.data_in_interval_schema import DataInIntervalSchema

class GatewayIntervalConsumptionSchema(BaseModel):
    """
    GatewayIntervalConsumptionSchema
    """
    sm_id: Optional[StrictStr] = Field(default=None, alias="smId")
    var_from: Optional[datetime] = Field(default=None, alias="from")
    to: Optional[datetime] = None
    interval: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="interval in seconds")
    data: Optional[conlist(DataInIntervalSchema)] = None
    __properties = ["smId", "from", "to", "interval", "data"]

    class Config:
        """Pydantic configuration"""
        populate_by_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GatewayIntervalConsumptionSchema:
        """Create an instance of GatewayIntervalConsumptionSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item in self.data:
                if _item:
                    _items.append(_item.to_dict())
            _dict['data'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GatewayIntervalConsumptionSchema:
        """Create an instance of GatewayIntervalConsumptionSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GatewayIntervalConsumptionSchema.parse_obj(obj)

        _obj = GatewayIntervalConsumptionSchema.parse_obj({
            "sm_id": obj.get("smId"),
            "var_from": obj.get("from"),
            "to": obj.get("to"),
            "interval": obj.get("interval"),
            "data": [DataInIntervalSchema.from_dict(_item) for _item in obj.get("data")] if obj.get("data") is not None else None
        })
        return _obj


