# coding: utf-8

"""
    Solar Manager external API 

    This is a Solar Manager external communication service

    The version of the OpenAPI document: 1.19.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr
from openapi_client.models.model31 import Model31

class Model32(BaseModel):
    """
    Model32
    """
    time: Optional[StrictStr] = None
    price: Optional[Union[StrictFloat, StrictInt]] = None
    tariff: Optional[Model31] = None
    __properties = ["time", "price", "tariff"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Model32:
        """Create an instance of Model32 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Model32:
        """Create an instance of Model32 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Model32.parse_obj(obj)

        _obj = Model32.parse_obj({
            "time": obj.get("time"),
            "price": obj.get("price"),
            "tariff": obj.get("tariff")
        })
        return _obj


