# coding: utf-8

"""
    Solar Manager external API 

    This is a Solar Manager external communication service

    The version of the OpenAPI document: 1.19.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from openapi_client.models.model4 import Model4

class Model6(BaseModel):
    """
    Model6
    """
    sensor_id: Optional[StrictStr] = Field(default=None, alias="sensorId")
    device_type: Optional[StrictStr] = None
    sub_meter_cost_types: Optional[StrictInt] = Field(default=None, alias="subMeterCostTypes")
    device_identification: Optional[StrictStr] = Field(default=None, alias="deviceIdentification")
    data: Optional[conlist(Model4)] = None
    __properties = ["sensorId", "device_type", "subMeterCostTypes", "deviceIdentification", "data"]

    class Config:
        """Pydantic configuration"""
        populate_by_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Model6:
        """Create an instance of Model6 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item in self.data:
                if _item:
                    _items.append(_item.to_dict())
            _dict['data'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Model6:
        """Create an instance of Model6 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Model6.parse_obj(obj)

        _obj = Model6.parse_obj({
            "sensor_id": obj.get("sensorId"),
            "device_type": obj.get("device_type"),
            "sub_meter_cost_types": obj.get("subMeterCostTypes"),
            "device_identification": obj.get("deviceIdentification"),
            "data": [Model4.from_dict(_item) for _item in obj.get("data")] if obj.get("data") is not None else None
        })
        return _obj


